set dotenv-load

# build lambda
build:
  cargo lambda build --release

# deploy lambda
deploy bin: build
  cargo lambda deploy --s3-bucket xf-rust {{bin}}

# clean everything
clean:
  cargo cache -a
  cargo clean
  rm Cargo.lock

# install tools
tools:
  cargo install cargo-lambda
  cargo install just
