set dotenv-load

# build lambda
build:
  cargo lambda build

# deploy lambda
deploy bin: build
  cargo lambda deploy {{bin}}  

# clean everything
clean:
  cargo cache -a
  cargo clean
  rm Cargo.lock

# install tools
tools:
  cargo install cargo-lambda
