set dotenv-load

# build lambda
build:
  cargo lambda build --release

# deploy lambda
deploy bin: build
  cargo lambda deploy --s3-bucket xf-rust {{bin}}

# test dbimporter
test:
  curl \
    --header "Content-Type: application/json" \
    --request POST \
    --data '[ { "symbol": "SPY", "time": 1660229200, "prices": "eyJyZWd1bGFyTWFya2V0UHJpY2UiOjQxOS43OCwicHJldmlvdXNDbG9zZSI6NDIwLjAwfQ==" }, { "symbol": "SPY", "time": 1660142800, "prices": "eyJyZWd1bGFyTWFya2V0UHJpY2UiOjQxMi42NywicHJldmlvdXNDbG9zZSI6NDE5LjMzfQ==" }, { "symbol": "SPY", "time": 1660056400, "prices": "eyJyZWd1bGFyTWFya2V0UHJpY2UiOjQxOC4xMiwicHJldmlvdXNDbG9zZSI6NDE4Ljk4fQ==" } ]' \
    https://ulrxqeyrkw3wbqjnwk4bkyx47a0dbsbn.lambda-url.us-east-1.on.aws

# clean everything
clean:
  cargo cache -a
  cargo clean
  rm Cargo.lock

# install tools
tools:
  cargo install cargo-lambda
  cargo install just e
