[package]
name = "events-b"
authors.workspace = true
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
aws_lambda_events.workspace = true
lambda_runtime.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
